blank_issues_enabled: false
contact_links:
- name: 💬 Community Forum
  url: https://www.reddit.com/r/EXygnus/
  about: Ask the community for help on our forum.
- name: ❔ Support Question
  url: https://www.reddit.com/r/EXygnus/
  about: This repository is only for reporting bugs or feature requests, please create a support ticket if you need any assistance from our team.
